name: NodeJS with Webpack

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.0, 22.17.0]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: NPM Install
      run: npm install

    - name: ESLint
      run: npm run test:lint
     
    - name: Build
      run: |
        npx webpack
