name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: npm install
        run: npm install --frozen-lockfile
      - name: npm link & build
        run: |
          cd scratch-vm
          npm link
          cd ../pmt-gui
          npm link scratch-vm
          npm run build
