name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    outputs:
      pmt-gui-artifact: pmt-gui-node-modules
      scratch-vm-artifact: scratch-vm-node-modules
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: |
          cd scratch-vm
          npm install --frozen-lockfile
          cd ../pmt-gui
          npm install --frozen-lockfile
          cd ..
      - name: lint scratch-vm
        run: |
          cd scratch-vm
          npm run lint
          npm link
          cd ..
      - name: lint pmt-gui
        run: |
          cd pmt-gui
          npm run test:lint
          npm link scratch-vm
          cd ..
      - name: build pmt-gui
        run: |
          cd pmt-gui
          npm run build
      - name: Archive build output
        run: |
          tar -czf ${{ github.sha }}.tar.gz -C pmt-gui/dist .
      - name: Copy artifact to server
        run: |
          scp -P ${{ secrets.VPS_PORT }} -i ~/.ssh/id_rsa ${{ github.sha }}.tar.gz ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/tmp/${{ github.head_ref || github.ref_name }}.tar.gz
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            TARGET="${{ github.event_name == 'pull_request' && format('PR-{0}', github.event.number) || github.ref_name }}"
            /home/scripts/deploy.sh "$TARGET"
