name: CI Pages

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            scratch-vm/package-lock.json
            pmt-gui/package-lock.json

      - name: Install scratch-vm dependencies
        working-directory: scratch-vm
        run: npm install

      - name: Lint scratch-vm
        working-directory: scratch-vm
        run: npm run lint

      - name: Link scratch-vm
        working-directory: scratch-vm
        run: npm link

      - name: Install pmt-gui dependencies
        working-directory: pmt-gui
        run: npm install

      - name: Lint pmt-gui
        working-directory: pmt-gui
        run: npm run test:lint

      - name: Link scratch-vm into pmt-gui
        working-directory: pmt-gui
        run: npm link scratch-vm

      - name: Build pmt-gui
        working-directory: pmt-gui
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload GitHub Pages artifact (pmt-gui/build)
        uses: actions/upload-pages-artifact@v3
        with:
          path: pmt-gui/build

  deploy:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
