name: CI Pages

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: |
          cd scratch-vm
          npm install --frozen-lockfile
          cd ../pmt-gui
          npm install --frozen-lockfile
          cd ..
      - name: lint scratch-vm
        run: |
          cd scratch-vm
          npm run lint
          npm link
          cd ..
      - name: lint pmt-gui
        run: |
          cd pmt-gui
          npm run test:lint
          npm link scratch-vm
          cd ..
      - name: build pmt-gui
        run: |
          cd pmt-gui
          npm run build
      - name: Add .nojekyll
        run: |
          touch pmt-gui/build/.nojekyll
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload GitHub Pages artifact (pmt-gui/build)
        uses: actions/upload-pages-artifact@v3
        with:
          path: pmt-gui/build

  deploy:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
